<?php
require 'C:\xampp\htdocs\AppWebIntermedia\src\models\Pedido.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-20 at 00:11:08.
 */
class PedidoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Pedido
     */
    protected $object;
    private $conn;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Pedido;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function getConnection(){
        
    }

    /**
     * @covers Pedido::setAttributes
     * @todo   Implement testSetAttributes().
     */
    public function testSetAttributes() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(1,1);
    }

    /**
     * @covers Pedido::getAttributes
     * @todo   Implement testGetAttributes().
     */
    public function testGetAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pedido::listPedidosOfConc
     * @todo   Implement testListPedidosOfConc().
     */
    public function testListPedidosOfConc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pedido::loadPedido
     * @todo   Implement testLoadPedido().
     */
    public function testLoadPedido() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pedido::insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
